name: CI/CD Pipeline - DAY 35 Assignment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      day35-changed: ${{ steps.changes.outputs.day35 }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to ensure we can compare commits

      - name: Check for changes in DAY 35 folder
        id: changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "^DAY 35 \[ CI-CD \]/Assignment/"; then
            echo "day35=true" >> $GITHUB_OUTPUT
          else
            echo "day35=false" >> $GITHUB_OUTPUT
          fi

  build-test-deploy:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.day35-changed == 'true'
    
    defaults:
      run:
        working-directory: "DAY 35 [ CI-CD ]/Assignment"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: JDK 21 Setup
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn test

      - name: Build JAR
        run: mvn package -DskipTests

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/day35-cicd-demo:latest .

      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image To Dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/day35-cicd-demo:latest

      - name: Tag and push with SHA
        run: |
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/day35-cicd-demo:latest ${{ secrets.DOCKERHUB_USERNAME }}/day35-cicd-demo:${{ github.sha }}
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/day35-cicd-demo:${{ github.sha }}
